In [4]:
import numpy as np

In [81]:
class KNearestNeighbours:
    def __init__(self, k: int = 1) -> None:
        self.k = k

    def fit(self, X, y):
        self.neighbours = [[] for _ in range(len(X))]
        self.predictions = []
        self.X = X
        for i, x in enumerate(X):
            distences = []
            for j, x1 in enumerate(X):
                distence = np.linalg.norm(x - x1)
                distences.append((distence, j))
            distences = sorted(distences)
            for k in range(self.k):
                self.neighbours[i].append((distences[k+1][1]))
        for ele in self.neighbours:
            y_pred = sum([y[ele[i]] for i in range(len(ele))]) / self.k
            self.predictions.append(y_pred)
        
                
    def predict(self, X):
        predictions = []
        neighbours = [[] for _ in range(len(X))]
        for i, x in enumerate(X):
            distences = []
            for j, x1 in enumerate(self.X):
                distence = np.linalg.norm(x - x1)
                distences.append((distence, j))
            distences = sorted(distences)
            for k in range(self.k):
                neighbours[i].append((distences[k+1][1]))
        for ele in neighbours:
            for i in range(len(self.neighbours)):
                if sorted(ele) == self.neighbours[i]:
                    predictions.append(self.predictions[i])
                else: 
                    continue
        return predictions
        

In [56]:
x = np.arange(1, 21)
x1 = []
for ele in x:
    x1.append(np.array([ele, ele]))
x1

[array([1, 1]),
 array([2, 2]),
 array([3, 3]),
 array([4, 4]),
 array([5, 5]),
 array([6, 6]),
 array([7, 7]),
 array([8, 8]),
 array([9, 9]),
 array([10, 10]),
 array([11, 11]),
 array([12, 12]),
 array([13, 13]),
 array([14, 14]),
 array([15, 15]),
 array([16, 16]),
 array([17, 17]),
 array([18, 18]),
 array([19, 19]),
 array([20, 20])]

In [16]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
model = KNearestNeighbours(2)
model.fit(x1, x)
X = [(3, 3), (2.2, 2.2)]
model.predict(X)

[3.0, 2.0]

In [83]:
model.predictions

[2.5,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 18.5]